private: false
customLibraries:
  array:
    - object:
        version: 4.18.1
        language: javascript
        variable: _
        codeString: |
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: lodash
    - object:
        version: 2.1.0
        language: javascript
        variable: numbro
        codeString: |
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: numbro
    - object:
        version: 5.3.2
        language: javascript
        variable: Papa
        codeString: |
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: papaparse
    - object:
        version: 0.5.23
        language: javascript
        variable: moment
        codeString: |
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: moment-timezone
    - object:
        version: 3.4.0
        language: javascript
        variable: uuid
        codeString: |
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
        libraryName: uuid
name: test workflow 1
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: |
          // lodash
          /* Edit library variable below */

          const _ = require('lodash')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // numbro
          /* Edit library variable below */

          const numbro = require('numbro')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // papaparse
          /* Edit library variable below */

          const Papa = require('papaparse')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // moment-timezone
          /* Edit library variable below */

          const moment = require('moment-timezone')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */

          // uuid
          /* Edit library variable below */

          const uuid = require('uuid')

          /* Add destructured imports from library below
          eg. const { pow, log } = require("mathjs") */
hasProtectedTriggers: true
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: 0109fd93-958c-41c0-8523-a99c7f808ee4
description: ''
workflowTemplate:
  version: 3.386.0
